
package ec.ups.edu.EVA_ReinosoJoseph_CLI.soap;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import ec.ups.edu.EVA_ReinosoJoseph_CLI.view.ventanIngresar;

/**
 * This class was generated by Apache CXF 3.5.0
 * 2022-02-01T11:55:50.739-05:00
 * Generated source version: 3.5.0
 *
 */
public final class ObrasServiceSOAP_ObrasServiceSOAPPort_Client {

    private static final QName SERVICE_NAME = new QName("http://bean.EVA_ReinosoJoseph_SRV.ups.edu.ec/", "ObrasServiceSOAPService");
    

    public ObrasServiceSOAP_ObrasServiceSOAPPort_Client() {
    
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ObrasServiceSOAPService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        ObrasServiceSOAPService ss = new ObrasServiceSOAPService(wsdlURL, SERVICE_NAME);
        ObrasServiceSOAP port = ss.getObrasServiceSOAPPort();

        {
        	// TODO Auto-generated method stub
    		System.out.println("Invoking crearObra...");
    		ObrasArte o = new ObrasArte();
            ec.ups.edu.EVA_ReinosoJoseph_CLI.soap.ObrasArte obra = o;
            
    		java.lang.String _crearObra__return = port.crearObra(obra);
            System.out.println("crearObra.result=" + _crearObra__return);
        }
        
        {
        System.out.println("Invoking getObras...");
        java.util.List<ec.ups.edu.EVA_ReinosoJoseph_CLI.soap.ObrasArte> _getObras__return = port.getObras();
        System.out.println("getObras.result=" + _getObras__return);

        }

        System.exit(0);
    }

}
